Web/assignment/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

app_name = 'assignment'
urlpatterns = [
     url(r'^$', views_cbv.assignment_list, name = 'assignment_list'),
     url(r'^(?P<id>\d+)/$', views.assignment_detail, name = 'assignment_detail'),
     url(r'^new/$', views.assignment_new, name ='assignment_new'),
     url(r'^(?P<id>\d+)/edit/$', views.assignment_edit, name = 'assignment_edit'),


     url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.assignment_delete, name ='assignment_delete'),
]

Web/capstone/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.conf.urls.static import static

def root(request):
    return redirect('ifb:first_page')



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', root, name='root'),
    url(r'^IFB/', include('ifb.urls', namespace='ifb')),

    #IFB398
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^assignment/', include('assignment.urls', namespace='assignment')),
    url(r'^reflection/', include('reflection.urls', namespace='reflection')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    #url('', include('social_django.urls', namespace='social')),


    #IFB399
    url(r'^assignment399/', include('assignment399.urls', namespace='assignment399')),
    url(r'^reflection399/', include('reflection399.urls', namespace='reflection399')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     import debug_toolbar
     urlpatterns += [
     url(r'^__debug__/', include(debug_toolbar.urls)),
     ]

Web/ifb/urls.py
from django.conf.urls import url
from . import views


app_name = 'ifb'

urlpatterns = [
     url(r'^$', views.first_page, name = 'first_page'),
     url(r'^IFB398/$', views.ifb398_first_page, name = 'ifb398_first_page'),
     url(r'^IFB399/$', views.ifb399_first_page, name = 'ifb399_first_page'),
]

Web/assignment/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
# Create your models here.

def user_validator(value):
    if not re.match('admin', value):
        raise ValidationError('Invalid LngLat Type')

STATUS_CHOICES = (
     ('d', 'Draft'),
     ('p', 'Published'),
     ('w', 'Withdrawn'), )

class Assignment(models.Model):
    #author = models.CharField(max_length=20)
    user =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, verbose_name = 'Title')
    content = models.TextField(verbose_name ='Content')
    document = models.FileField(blank = True, upload_to='assignment/documents/%Y/%m')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

#form 작성시 이게 있어야 저장됨
    def get_absolute_url(self):
        return reverse('assignment:assignment_detail', args=[self.id])

Web/project/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
# Create your models here.

def lnglat_validator(value):
    if not re.match(r'^(\d+\.?\d*),(\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

STATUS_CHOICES = (
     ('d', 'Draft'),
     ('p', 'Published'),
     ('w', 'Withdrawn'), )

INDUSTRY_CHOICES = (
     ('Web Application', 'Web Application'),
     ('Mobile Application', 'Mobile Application'),
     ('Software', 'Software'),
     ('Hardware', 'Hardware'),
     ('Data', 'Data'), )

class Post(models.Model):
    #author = models.CharField(max_length=20)
    user =models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
    title = models.CharField(max_length=100, verbose_name = 'Title')
    content = models.TextField(verbose_name ='Content', help_text = ('Please describe your project'))
    document = models.FileField(blank = True, upload_to='project/documents/%Y/%m')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    category = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']


    def __str__(self):
        return self.title

#form 작성시 이게 있어야 저장됨
    def get_absolute_url(self):
        return reverse('project:post_detail', args=[self.id])

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.PROTECT)
    author = models.CharField(max_length=20)
    message = models.TextField()
    document = models.FileField(blank = True, upload_to='project/documents/%Y/%m')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

Web/assignment/forms.py
from django import forms
from .models import Assignment


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = '__all__'

Web/assignment/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Assignment
from django.http import Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from .forms import AssignmentForm
from django.views.generic import CreateView,ListView,DetailView,UpdateView, DeleteView
from django.contrib import messages
# Create your views here.

def assignment_list(request):
    qs = Assignment.objects.all() # 교수들이 어드민에 올린거 이런식으로 받아오기

    q = request.GET.get('q','')
    if q:
        qs=qs.filter(title__icontains=q)

    return render(request, 'assignment/assignment_list.html', {'assignment_list':qs, 'q':q, })

def assignment_detail(request,id):
#    post=Post.objects.get(id=id)
    assignment = get_object_or_404(Assignment, id=id)
    return render(request, 'assignment/assignment_detail.html',{'assignment':assignment })


def assignment_new(request):
    if request.method=='POST':
        form = AssignmentForm(request.POST,request.FILES)
        if form.is_valid():
            assignment=form.save()
            messages.success(request,'New post was saved')
            return redirect(assignment) #post.get_absoluteurl() => post detail view 고쳐야함;; 모르겠다
    else:
        form=AssignmentForm()
    return render(request,'assignment/assignment_form.html', {'form':form})

def assignment_edit(request,id):

    assignment = get_object_or_404(Assignment, id=id)
    if request.method=='POST':
        form = AssignmentForm(request.POST,request.FILES, instance=assignment)
        if form.is_valid():
            assignment=form.save()
            return redirect(assignment) #post.get_absoluteurl() => post detail view
    else:
        form = AssignmentForm(instance=assignment)
    return render(request,'assignment/assignment_form.html', {'form':form,})

Web/assignment/templates/assignment/assignment_confirm_delete.html
<h1>{{assignment}} Confirm to Delete</h1>

Do you want to really delete this post??

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes"/>
</form>

Web/assignment/templates/assignment/assignment_detail.html
{% extends "assignment/layout.html" %}


{%block title%}
  {{assignment.title}}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-sm-12">

        <h2>Assignment {{assignment.id}} {{assignment.title}}</h2>
        Assignment Description: {{assignment.content|linebreaks}}

        {% if assignment.document %}
        <li>
        <a href="{{ assignment.document.url }}">{{ assignment.document.name }}</a>
        </li>
        {% endif %}

        <hr/>
        <h3>COMMENTS</h3>
        <ul>
          {% for comment in assignment.comment_set.all %}
          <li>
            {{comment.message}}
            <small>{{comment.author}}</small>
            <small>at {{ comment.updated_at }}</small>
          </li>
          {%endfor%}
        </ul>

          <hr/>
          <a href="{% url "assignment:assignment_list" %}" class ="btn btn-primary">List</a>
          <a href="{% url "assignment:assignment_edit" assignment.id %}" class ="btn btn-default">Edit</a>
          <a href="{% url "assignment:assignment_delete" assignment.id %}" class ="btn btn-default">Delete</a>
      </div>

    </div>

  </div>


{% endblock %}

Web/assignment/templates/assignment/assignment_form.html
{% extends "assignment/layout.html" %}
 {% load bootstrap3 staticfiles %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}

 {% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-5 col-sm-6 col-lg-4 " >
      <legend>Assigment Form</legend>
        <form class="form-horizontal" enctype="multipart/form-data" action="" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" class="btn btn-primary" name="" value="Submit">
        </form>
        </div>
    </div>
</div>

{% endblock %}

Web/assignment/templates/assignment/assignment_list.html
{% extends "assignment/layout.html" %}

{% load bootstrap3 staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Capstone Assignment</h1>
            <p>QUT - IFB</p>
            <p>
                <a class="btn btn-lg btn-primary" href="/project/">
                        Project &raquo;
                    </a>

                <a class="btn btn-lg btn-primary" href="/reflection/">
                        Reflection &raquo;
                        </a>

            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <a href="{% url "assignment:assignment_new" %}" class = "btn btn-primary pull-right">New Assignment</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Assignment Number</th>
                            <th>Assignment Name</th>
                            <th>Uploaded</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for assignment in assignment_list %}
                            <tr>
                                <td>{{ assignment.id }}</td>
                                <td><a href="{% url "assignment:assignment_detail" assignment.id %}">{{ assignment.title }}</a></td>
                                <td><small>at {{ assignment.updated_at }}</small></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="text-center">
                    {% bootstrap_pagination page_obj %}
                </div>
            </div>
        </div>

    </div>


{% endblock %}

Web/assignment/templates/assignment/layout.html
{% extends "layout.html" %}

{%block title%} QUT_IFB {%endblock%}