Web/capstone/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.conf.urls.static import static

def root(request):
    return redirect('ifb:first_page')



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', root, name='root'),
    url(r'^IFB/', include('ifb.urls', namespace='ifb')),

    #IFB398
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^assignment/', include('assignment.urls', namespace='assignment')),
    url(r'^reflection/', include('reflection.urls', namespace='reflection')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    #url('', include('social_django.urls', namespace='social')),


    #IFB399
    url(r'^assignment399/', include('assignment399.urls', namespace='assignment399')),
    url(r'^reflection399/', include('reflection399.urls', namespace='reflection399')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     import debug_toolbar
     urlpatterns += [
     url(r'^__debug__/', include(debug_toolbar.urls)),
     ]

Web/ifb/urls.py
from django.conf.urls import url
from . import views


app_name = 'ifb'

urlpatterns = [
     url(r'^$', views.first_page, name = 'first_page'),
     url(r'^IFB398/$', views.ifb398_first_page, name = 'ifb398_first_page'),
     url(r'^IFB399/$', views.ifb399_first_page, name = 'ifb399_first_page'),
]

Web/project/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

app_name = 'project'
urlpatterns = [
     url(r'^$', views_cbv.post_list, name = 'post_list'),
     #url(r'^$', views.post_list, name = 'post_list'),

     url(r'^(?P<id>\d+)/$', views.post_detail, name = 'post_detail'),
     url(r'^new/$', views.post_new, name ='post_new'),
     url(r'^(?P<id>\d+)/edit/$', views.post_edit, name = 'post_edit'),

     url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name ='post_delete'),

     url(r'^post/(?P<pk>[0-9]+)/commentnew/$', views.comment_new, name ='comment_new'),
     url(r'^comments/$', views.comment_list, name='comment_list'),

     #url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),

     url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
     url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

Web/project/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
# Create your models here.

def lnglat_validator(value):
    if not re.match(r'^(\d+\.?\d*),(\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

STATUS_CHOICES = (
     ('d', 'Draft'),
     ('p', 'Published'),
     ('w', 'Withdrawn'), )

INDUSTRY_CHOICES = (
     ('Web Application', 'Web Application'),
     ('Mobile Application', 'Mobile Application'),
     ('Software', 'Software'),
     ('Hardware', 'Hardware'),
     ('Data', 'Data'), )

class Post(models.Model):
    #author = models.CharField(max_length=20)
    user =models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
    title = models.CharField(max_length=100, verbose_name = 'Title')
    content = models.TextField(verbose_name ='Content', help_text = ('Please describe your project'))
    document = models.FileField(blank = True, upload_to='project/documents/%Y/%m')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    category = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']


    def __str__(self):
        return self.title

#form 작성시 이게 있어야 저장됨
    def get_absolute_url(self):
        return reverse('project:post_detail', args=[self.id])

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.PROTECT)
    author = models.CharField(max_length=20)
    message = models.TextField()
    document = models.FileField(blank = True, upload_to='project/documents/%Y/%m')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

Web/project/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','message','document')

Web/project/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post, Comment
from django.http import Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.views.generic import CreateView,ListView,DetailView,UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
# Create your views here.

#Post view Line and Number


def post_list(request):

    qs = Post.objects.all().prefetch_related('comment_set') # 교수들이 어드민에 올린거 이런식으로 받아오기

    q = request.GET.get('q','')
    if q:
        qs=qs.filter(title__icontains=q)

    return render(request, 'project/post_list.html', {'post_list':qs, 'q':q, })

def post_detail(request,id):
#    post=Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id)
    return render(request, 'project/post_detail.html',{'post':post ,})


def post_new(request):
    if request.method=='POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save()
            messages.success(request,'New post was saved')
            return redirect(post) #post.get_absoluteurl() => post detail view
    else:
        form=PostForm()
    return render(request,'project/post_form.html', {'form':form})


def post_edit(request,id):

    post = get_object_or_404(Post, id=id)
    if request.method=='POST':
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post=form.save()
            messages.success(request,'New post was edited')
            return redirect(post) #post.get_absoluteurl() => post detail view
    else:
        form = PostForm(instance=post)
    return render(request,'project/post_form.html', {'form':form,})


def comment_list(request):
    comment_list = Comment.objects.all().select_related('post')
    return render(request, 'project/comment_list.html', {'comment_list':comment_list,
    })

def comment_new(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method=='POST':
        form = CommentForm(request.POST,request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            #messages.success(request,'New application was saved')
            return redirect('project:post_detail',post.pk) #post.get_absoluteurl() => post detail view
    else:
        form=CommentForm()
    return render(request,'project/comment_form.html', {'form':form})
'''
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST,request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('project:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'project/add_comment_to_post.html', {'form': form})
'''
@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('project:post_detail', comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('project:post_detail', comment.post.pk)

Web/project/templates/project/add_comment_to_post.html
{% extends 'project/layout.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

Web/project/templates/project/comment_form.html
{% extends "project/layout.html" %}
 {% load bootstrap3 staticfiles %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}

 {% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-5 col-sm-6 col-lg-4 " >
      <legend>Application Form</legend>
      <form class="form-horizontal" enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" name="" value="Submit">
      </form>
      </div>

    </div>

  </div>

{%endblock%}

Web/project/templates/project/comment_list.html
{%extends "project/layout.html"%}
{% block content %}
<ul>
  {% for comment in comment_list %}
  <li>
    {{comment}}
    {{comment.post}}
  </li>
  {% endfor %}
</ul>

{% endblock %}

Web/project/templates/project/layout.html
{% extends "layout.html" %}

{%block title%} QUT_IFB {%endblock%}

Web/project/templates/project/post_confirm_delete.html
<h1>{{post}} Confirm to Delete</h1>

Do you want to really delete this post??

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes"/>
</form>

Web/project/templates/project/post_detail.html
{% extends "project/layout.html" %}

{%block title%}
  {{post.title}}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-sm-12">

          <h2>Project {{ post.id }}: {{post.title}}</h2>
          Project Description: {{post.content|linebreaks}}

        <hr/>
        <h3>File</h3>
        {% if post.document %}
        <a href="{{ post.document.url }}" class ="btn btn-default">download</a>
        {% endif %}

        <hr/>
        <h3><a href="{% url "project:comment_new" pk=post.pk %}" class ="btn btn-primary">  Apply</a></h3>

        <ul>

          {% for comment in post.comment_set.all %}
          {% if user.is_authenticated or comment.approved_comment %}
          <li>
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url "project:comment_remove" pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>

            {% endif %}
            {{comment.message}}
            {% if comment.document %}
            <a href="{{ comment.document.url }}" class ="btn btn-default">File</a>
            {% endif %}
            <small>{{comment.author}}</small>
            <small>at {{ comment.updated_at }}</small>


          </li>
          {% endif %}
          {% endfor %}
        </ul>


          <hr/>
          <a href="{% url "project:post_list" %}" class ="btn btn-primary">List</a>
          <a href="{% url "project:post_edit" post.id %}" class ="btn btn-default">Edit</a>
          <a href="{% url "project:post_delete" post.id %}" class ="btn btn-default">Delete</a>
<!--
          <hr/>
          {% for comment in post.comments.all %}
            {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
              <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                  <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                  <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
    <p>No comments here yet :(</p>
    {% endfor %}
-->

      </div>

    </div>

  </div>


{% endblock %}

Web/project/templates/project/post_form.html
{% extends "project/layout.html" %}
 {% load bootstrap3 staticfiles %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}

 {% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-sm-6 col-lg-4 " >
      <legend>Project Form</legend>
      <form class="form-horizontal" enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" name="" value="Submit">
      </form>
      </div>

    </div>

  </div>
{% endblock %}

Web/project/templates/project/post_list.html
{% extends "project/layout.html" %}

{% load bootstrap3 staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Capstone Project</h1>
            <p>QUT - IFB398</p>
            <p>
              <a class="btn btn-lg btn-primary" href="/assignment/">
                      Assignment &raquo;
                      </a>
              <a class="btn btn-lg btn-primary" href="/reflection/">
                              Reflection &raquo;
                              </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">

                <a href="{% url "project:post_new" %}" class = "btn btn-primary pull-right">New Post</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </form>
                </p>

                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>

                          <th>Project Number</th>
                          <th>Project Name</th>
                          <th>Project Owner</th>
                          <th>Uploaded at</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                            <tr>
                                <td><a href="{% url "project:post_detail" post.id %}">{{ post.title }}</a></td>
                                <td>{{ post.category }}</td>
                                <td><small>by {{ post.user }}</small></td>
                                <td><small>at {{ post.updated_at }}</small></td>

                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                  <div class="text-center">
                      {% bootstrap_pagination page_obj %}
                  </div>
            </div>
        </div>

    </div>


{% endblock %}