Web/capstone/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.conf.urls.static import static

def root(request):
    return redirect('ifb:first_page')



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', root, name='root'),
    url(r'^IFB/', include('ifb.urls', namespace='ifb')),

    #IFB398
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^assignment/', include('assignment.urls', namespace='assignment')),
    url(r'^reflection/', include('reflection.urls', namespace='reflection')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    #url('', include('social_django.urls', namespace='social')),


    #IFB399
    url(r'^assignment399/', include('assignment399.urls', namespace='assignment399')),
    url(r'^reflection399/', include('reflection399.urls', namespace='reflection399')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     import debug_toolbar
     urlpatterns += [
     url(r'^__debug__/', include(debug_toolbar.urls)),
     ]

Web/ifb/urls.py
from django.conf.urls import url
from . import views


app_name = 'ifb'

urlpatterns = [
     url(r'^$', views.first_page, name = 'first_page'),
     url(r'^IFB398/$', views.ifb398_first_page, name = 'ifb398_first_page'),
     url(r'^IFB399/$', views.ifb399_first_page, name = 'ifb399_first_page'),
]

Web/reflection/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

app_name = 'reflection'
urlpatterns = [
     url(r'^$', views.reflection_list, name = 'reflection_list'),
     url(r'^(?P<id>\d+)/$', views.reflection_detail, name = 'reflection_detail'),
     url(r'^new/$', views.reflection_new, name ='reflection_new'),
     url(r'^(?P<id>\d+)/edit/$', views.reflection_edit, name = 'reflection_edit'),
     url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.reflection_delete, name ='reflection_delete'),
]

Web/reflection/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


STATUS_CHOICES = (
     ('d', 'Draft'),
     ('p', 'Published'),)


class Reflection(models.Model):
    #author = models.CharField(max_length=20)
    title = models.CharField(max_length=20, verbose_name = 'title')
    team_number  = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(50)], blank=True, null=True)
    week = models.IntegerField(default=2, validators=[MinValueValidator(2), MaxValueValidator(12)], blank=True, null=True)
    student_name = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
    #student_name = models.OneToOneField(User, on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(7)], help_text ='Reflect on how well you delivered your product')
    self_reflection = models.TextField(verbose_name ='Self-reflection',help_text ='Reflect on how you delivered on your three main tasks for the last fortnight')
    self_plan = models.TextField(verbose_name ='Detail your three main tasks for the next fortnight',help_text ='Detail your three main tasks for the next fortnight')


    team1_name= models.CharField(max_length=100, verbose_name = 'Student 1 Name')
    team1_grade = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(7)], help_text ='Grade between 1 and 7')
    team1_reflection = models.TextField(verbose_name ='Evaluation of contribution and performance')

    team2_name = models.CharField(max_length=100, verbose_name = 'Student 2 Name')
    team2_grade = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(7)], help_text ='Grade between 1 and 7')
    team2_reflection = models.TextField(verbose_name ='Evaluation of contribution and performance')

    team3_name = models.CharField(max_length=100, verbose_name = 'Student 3 Name')
    team3_grade = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(7)], help_text ='Grade between 1 and 7')
    team3_reflection = models.TextField(verbose_name ='Evaluation of contribution and performance')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    class Meta:
        ordering = ['-id']
        ordering = ['team_number']

    def __str__(self):
        return self.title

#form 작성시 이게 있어야 저장됨
    def get_absolute_url(self):
        return reverse('reflection:reflection_detail', args=[self.id])

Web/reflection/forms.py
from django import forms
from .models import Reflection

class ReflectionForm(forms.ModelForm):
    class Meta:
        model = Reflection
        fields = '__all__'




#    def __init__(self, user, *args, **kwargs):
#        super(ReflectionForm,self).__init__(*args, **kwargs)self.fields['student_name'].queryset = Member.objects.filter(user=user)

Web/reflection/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Reflection
from django.http import Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from .forms import ReflectionForm
from django.contrib import messages
from django.views.generic import CreateView,ListView,DetailView,UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.

def reflection_list(request):
    qs = Reflection.objects.all() # 교수들이 어드민에 올린거 이런식으로 받아오기
    q = request.GET.get('q','')
    if q:
        qs=qs.filter(team_number__icontains=q)

    return render(request, 'reflection/reflection_list.html', {'reflection_list':qs, 'q':q, })

def reflection_detail(request,id):
#    post=Post.objects.get(id=id)
    reflection = get_object_or_404(Reflection, id=id)
    return render(request, 'reflection/reflection_detail.html',{'reflection':reflection ,})


def reflection_new(request):
    users = User.objects.get(username=request.user.username)

    if request.method=='POST':
        form = ReflectionForm(request.POST,request.FILES)
        if form.is_valid():
            reflection=form.save()
            messages.success(request,'New reflection was saved')
            return redirect(reflection) #post.get_absoluteurl() => post detail view
    else:
        form=ReflectionForm()
    return render(request,'reflection/reflection_form.html', {'form':form})

def reflection_edit(request,id):
    reflection = get_object_or_404(Reflection, id=id)
    if request.method=='POST':
        form = ReflectionForm(request.POST,request.FILES, instance=reflection)
        if form.is_valid():
            reflection=form.save()
            messages.success(request,'New reflection was edited')
            return redirect(reflection) #post.get_absoluteurl() => post detail view
    else:
        form = ReflectionForm(instance=reflection)
    return render(request,'reflection/reflection_form.html', {'form':form,})

Web/reflection/templates/reflection/layout.html
{% extends "layout.html" %}

{%block title%} QUT_IFB {%endblock%}

Web/reflection/templates/reflection/reflection_confirm_delete.html
<h1>{{reflection}} Confirm to Delete</h1>

Do you want to really delete this reflection??

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes"/>
</form>

Web/reflection/templates/reflection/reflection_detail.html
{% extends "reflection/layout.html" %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-sm-12">
    
        <ul>

          <h2>Team Number : {{reflection.team_number}} , Week   {{reflection.week}}</h2>
            <hr>
            <h3>Self Reflection</h3>
            <h4>Student Name : {{reflection.student_name}}</h4>
            <h4>Grade : {{reflection.grade}}</h4>
            <h4>Reflect on how you delivered on your three main tasks for the last : </h4>
            <h4>{{reflection.self_reflection}}</h4>
            <h4>Detail your three main tasks for the next fortnight:</h4>
            <h4>{{reflection.self_plan}}</h4>
            <hr/>

            <h3>Team Reflection</h3>
            <h4>Student Name : {{reflection.team1_name}}</h4>
            <h4>Grade : {{reflection.team1_grade}}</h4>
            <h4>Evaluation of contribution and performance :</h4>
            <h4>{{reflection.team1_reflection}}</h4>

            <br><br>

            <h4>Student Name : {{reflection.team2_name}}</h4>
            <h4>Grade : {{reflection.team2_grade}}</h4>
            <h4>Evaluation of contribution and performance :</h4>
            <h4>{{reflection.team2_reflection}}</h4>

            <br><br>

            <h4>Student Name : {{reflection.team3_name}}</h4>
            <h4>Grade : {{reflection.team3_grade}}</h4>
            <h4>Evaluation of contribution and performance :</h4>
            <h4>{{reflection.team3_reflection}}</h4>

        </ul>

          <hr/>
          <a href="{% url "reflection:reflection_list" %}" class ="btn btn-primary">List</a>
          <a href="{% url "reflection:reflection_edit" reflection.id %}" class ="btn btn-default">Edit</a>
          <a href="{% url "reflection:reflection_delete" reflection.id %}" class ="btn btn-default">Delete</a>
      </div>

    </div>

  </div>


{% endblock %}

Web/reflection/templates/reflection/reflection_form.html
{% extends "reflection/layout.html" %}
 {% load bootstrap3 staticfiles %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}

 {% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-5 col-sm-6 col-lg-4 " >

      <form class="" action="" method="post">
          <legend>Reflection Form</legend>
          {% csrf_token %}
          {% bootstrap_form form %}

          <input type="submit" class="btn btn-primary" name="" value="Submit">
        </form>
      </div>

    </div>

  </div>

{% endblock %}

Web/reflection/templates/reflection/reflection_list.html
{% extends "reflection/layout.html" %}

{% load bootstrap3 staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Capstone Reflection</h1>
            <p>QUT - IFB398</p>
            <p>
              <a class="btn btn-lg btn-primary" href="/project/">
                      Project &raquo;
                  </a>
              <a class="btn btn-lg btn-primary" href="/assignment/">
                      Assignment &raquo;
                      </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">

                <a href="{% url "reflection:reflection_new" %}" class = "btn btn-primary pull-right">New Reflection</a>

                <p>
                  <form action="" method="get">
                    TEAM
                      <input type="number" name="q" value="{{ q }}" />
                      <input type="submit" value="Search" class="btn btn-primary" />
                  </form>
                </p>


                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                          <th>Team number</th>
                          <th>Title</th>
                          <th>Week</th>
                          <th>Author</th>
                          <th>Uploaded</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reflection in reflection_list %}

                              <tr>
                                  <td>{{ reflection.team_number }}</td>
                                  <td><a href="{% url "reflection:reflection_detail" reflection.id %}">{{ reflection.title }}</a></td>
                                  <td>{{reflection.week}}</td>
                                  <td><small>by {{ reflection.student_name }}</small></td>
                                  <td><small>at {{ reflection.updated_at }}</small></td>
                              </tr>

                        {% endfor %}
                    </tbody>
                </table>


            </div>
        </div>

    </div>


{% endblock %}