Web/assignment399/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

app_name = 'assignment399'
urlpatterns = [
     url(r'^$', views_cbv.assignment399_list, name = 'assignment399_list'),
     url(r'^(?P<id>\d+)/$', views.assignment399_detail, name = 'assignment399_detail'),
     url(r'^new/$', views.assignment399_new, name ='assignment399_new'),
     url(r'^(?P<id>\d+)/edit/$', views.assignment399_edit, name = 'assignment399_edit'),


     url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.assignment399_delete, name ='assignment399_delete'),
]

Web/capstone/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.conf.urls.static import static

def root(request):
    return redirect('ifb:first_page')



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', root, name='root'),
    url(r'^IFB/', include('ifb.urls', namespace='ifb')),

    #IFB398
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^assignment/', include('assignment.urls', namespace='assignment')),
    url(r'^reflection/', include('reflection.urls', namespace='reflection')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    #url('', include('social_django.urls', namespace='social')),


    #IFB399
    url(r'^assignment399/', include('assignment399.urls', namespace='assignment399')),
    url(r'^reflection399/', include('reflection399.urls', namespace='reflection399')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     import debug_toolbar
     urlpatterns += [
     url(r'^__debug__/', include(debug_toolbar.urls)),
     ]

Web/ifb/urls.py
from django.conf.urls import url
from . import views


app_name = 'ifb'

urlpatterns = [
     url(r'^$', views.first_page, name = 'first_page'),
     url(r'^IFB398/$', views.ifb398_first_page, name = 'ifb398_first_page'),
     url(r'^IFB399/$', views.ifb399_first_page, name = 'ifb399_first_page'),
]

Web/assignment399/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
# Create your models here.

def user_validator(value):
    if not re.match('admin', value):
        raise ValidationError('Invalid LngLat Type')

STATUS_CHOICES = (
     ('d', 'Draft'),
     ('p', 'Published'),
     ('w', 'Withdrawn'), )

class Assignment399(models.Model):
    #author = models.CharField(max_length=20)
    user =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, verbose_name = 'Title')
    content = models.TextField(verbose_name ='Content')
    document = models.FileField(blank = True, upload_to='assignment399/documents/%Y/%m')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

#form 작성시 이게 있어야 저장됨
    def get_absolute_url(self):
        return reverse('assignment399:assignment399_detail', args=[self.id])

Web/assignment399/forms.py
from django import forms
from .models import Assignment399


class Assignment399Form(forms.ModelForm):
    class Meta:
        model = Assignment399
        fields = '__all__'

Web/assignment399/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Assignment399
from django.http import Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from .forms import Assignment399Form
from django.views.generic import CreateView,ListView,DetailView,UpdateView, DeleteView
# Create your views here.

def assignment399_list(request):
    qs = Assignment399.objects.all() # 교수들이 어드민에 올린거 이런식으로 받아오기

    q = request.GET.get('q','')
    if q:
        qs=qs.filter(title__icontains=q)

    return render(request, 'assignment399/assignment_list.html', {'assignment399_list':qs, 'q':q, })

def assignment399_detail(request,id):
#    post=Post.objects.get(id=id)
    assignment399 = get_object_or_404(Assignment399, id=id)
    return render(request, 'assignment399/assignment399_detail.html',{'assignment399':assignment399 })


def assignment399_new(request):
    if request.method=='POST':
        form = Assignment399Form(request.POST,request.FILES)
        if form.is_valid():
            assignment399=form.save()
            return redirect(assignment399) #post.get_absoluteurl() => post detail view 고쳐야함;; 모르겠다
    else:
        form=Assignment399Form()
    return render(request,'assignment399/assignment399_form.html', {'form':form})

def assignment399_edit(request,id):

    assignment399 = get_object_or_404(Assignment399, id=id)
    if request.method=='POST':
        form = Assignment399Form(request.POST,request.FILES, instance=assignment399)
        if form.is_valid():
            assignment399=form.save()
            return redirect(assignment399) #post.get_absoluteurl() => post detail view
    else:
        form = Assignment399Form(instance=assignment399)
    return render(request,'assignment399/assignment399_form.html', {'form':form,})

Web/assignment399/templates/assignment399/assignment399_confirm_delete.html
<h1>{{post}} Confirm to Delete</h1>

Do you want to really delete this post??

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes"/>
</form>

Web/assignment399/templates/assignment399/assignment399_detail.html
{% extends "assignment399/layout399.html" %}


{%block title%}
  {{assignment399.title}}

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-sm-12">

        <h2>Assignment {{assignment399.id}} {{assignment399.title}}</h2>
        Assignment Description: {{assignment399.content|linebreaks}}

        <hr/>
        {% if assignment399.document %}
        <h3>File</h3>
        <a href="{{ assignment399.document.url }}" class ="btn btn-default">download</a>
        {% endif %}


        <hr/>
          <hr/>
          <a href="{% url "assignment399:assignment399_list" %}" class ="btn btn-primary">List</a>
          <a href="{% url "assignment399:assignment399_edit" assignment399.id %}" class ="btn btn-default">Edit</a>
          <a href="{% url "assignment399:assignment399_delete" assignment399.id %}" class ="btn btn-default">Delete</a>
      </div>

    </div>

  </div>


{% endblock %}

Web/assignment399/templates/assignment399/assignment399_form.html
{% extends "assignment399/layout399.html" %}
 {% load bootstrap3 staticfiles %}
 {% bootstrap_css %}
 {% bootstrap_javascript %}

 {% block content %}

<div class="container">
  <div class="row">
    <div class="col-xs-5 col-sm-6 col-lg-4 " >
      <legend>Assigment Form</legend>
        <form class="form-horizontal" enctype="multipart/form-data" action="" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" class="btn btn-primary" name="" value="Submit">
        </form>
        </div>
    </div>
</div>

{% endblock %}

Web/assignment399/templates/assignment399/assignment399_list.html
{% extends "assignment399/layout399.html" %}

{% load bootstrap3 staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Capstone Assignment</h1>
            <p>QUT - IFB399</p>
            <p>
                <a class="btn btn-lg btn-primary" href="/reflection399/">
                                Reflection &raquo;
                                </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <a href="{% url "assignment399:assignment399_new" %}" class = "btn btn-primary pull-right">New Assignment</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                          <th>Assignment Number</th>
                          <th>Assignment Name</th>
                          <th>Uploaded</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for assignment399 in assignment399_list %}
                            <tr>

                                <td><a href="{% url "assignment399:assignment399_detail" assignment399.id %}">{{ assignment399.title }}</a></td>
                                <td><small>by {{ assignment399.user }}</small></td>
                                <td><small>at {{ assignment399.updated_at }}</small></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="text-center">
                    {% bootstrap_pagination page_obj %}
                </div>
            </div>
        </div>

    </div>


{% endblock %}

Web/assignment399/templates/assignment399/layout399.html
{% extends "layout399.html" %}

{%block title%} QUT_IFB {%endblock%}